import LegalPage from '../components/layout/LegalPage.jsx';

const Terms = () => (
  <LegalPage
    title="Terms of Service"
    updated="June 2026"
    intro="By using ClearLease, you agree to these terms. Please read them carefully."
    sections={[
      {
        heading: 'Acceptance of terms',
        body: 'By creating an account or using ClearLease, you agree to be bound by these Terms of Service and our Privacy Policy.',
      },
      {
        heading: 'Use of the service',
        body: [
          'You must provide accurate account information and keep your credentials secure.',
          'You may only upload lease documents that you have the right to analyze.',
          'You agree not to misuse, overload, or attempt to disrupt the service.',
        ],
      },
      {
        heading: 'Not legal advice',
        body: 'ClearLease provides automated, informational analysis only. It is not a law firm and does not provide legal advice. Always consult a licensed attorney before making binding decisions about a lease.',
      },
      {
        heading: 'AI-generated content',
        body: 'Analysis, chat answers, comparisons and negotiation letters are generated by AI and may contain errors or omissions. You are responsible for reviewing the original lease and verifying any output before acting on it.',
      },
      {
        heading: 'Accounts and termination',
        body: 'You are responsible for activity under your account. We may suspend or terminate accounts that violate these terms or misuse the service.',
      },
      {
        heading: 'Limitation of liability',
        body: 'ClearLease is provided "as is" without warranties of any kind. To the fullest extent permitted by law, we are not liable for any damages arising from your use of the service or reliance on its output.',
      },
      {
        heading: 'Changes to these terms',
        body: 'We may update these terms from time to time. Continued use of ClearLease after changes constitutes acceptance of the updated terms.',
      },
    ]}
  />
);

export default Terms;
